import 'package:flutter/material.dart';
class Avatars {
  final List<String> list = [
    'abacus',
    'ambulance',
    'apple',
    'atm',
    'atom',
    'barcode',
    'baseball',
    'basketball',
    'blaster',
    'boarding-ticket',
    'book',
    'bookmark',
    'brain',
    'brush',
    'bulls-eye',
    'car',
    'chemistry',
    'clock',
    'color-card',
    'cycle',
    'directions',
    'drink',
    'einstein',
    'equilizer',
    'factory',
    'ghost',
    'gift',
    'golf-ball',
    'graph',
    'id',
    'living-room',
    'man',
    'map',
    'mario',
    'mobile',
    'mouse',
    'passport',
    'pencil-brush',
    'perfume',
    'post-its',
    'purse',
    'sale',
    'sandels',
    'school-bus',
    'ship',
    'shower',
    'slippers',
    'stove',
    'swipe-card',
    'tap',
    'tetris',
    'travel-bag',
    'truck',
    'umbrella',
    'usb',
    'wallet',
    'water-bottle',
    'windmill',
    'woman',
    'yoga',
  ];

  static String getPathFromName(String name)=> 'images/avatars/$name.png';
  static Image getAssetFromName(String name) => Image.asset(getPathFromName(name));
}
